### PR TITLE
fix ch2.md: fix ch2 ambiguous translation

### PR DESCRIPTION
**Pull request by sunbuhui**
core 核心,kernel 内核. I think core is more like a word in hardware level , often is called "核心" in Chinese,  while kernel is the english of "内核", is used in operating system, a word in software level. Here the author talks about cpu core, i think "核心" will be better

### CODE REVIEW

**Review by Vonng — CHANGES_REQUESTED** [review]
That make sense~
But you can't include your own comment in PR....

**Comment by sunbuhui** [comment]
> That make sense~
> 
> But you can't include your own comment in PR....

Sorry , i committed my own comments to the wrong branch. I will correct it tomorrow. Thank you for your patience.

**Comment by sunbuhui** [comment]
@Vonng done, is this ok now?

**Comment by Vonng** [comment]
Thanks for your contribution~~

**Pull request merged**
